name: Tic-Tac-Toe
description: "Play Tic-Tac-Toe on your server"
version: 1.0
main: mavenmcserver.Plugin
api-version: 1.20

commands:
 tictactoe:
  description: "Start a new Tic-Tac-Toe game!"
  usage: "/<command> <opponent: Player> [sizeX = 3] [sizeY = 1] [sizeZ = 3] [winRequiredAmount = 3]"