name: "Build & Install action"
run-name: "Running Build & Install action (triggered by ${{ github.actor }})"
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: "Build print"
        run: "echo Build"
      - name: "Check out"
        uses: actions/checkout@v4
      - name: "Go to workspace directory /mavenmcserver"
        run: "cd ${{ github.workspace }}/mavenmcserver"
      - name: "List items here"
        run: "ls"
      - name: "Get maven version"
        run: "mvn --version"
  Install:
    runs-on: ubuntu-latest
    steps:
      - name: "Install print"
        run: "echo Install"
