name: "Build & Install action"
run-name: "Running Build & Install action (triggered by ${{ github.actor }})"
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: "Build print"
        run: "echo Build"
      - name: "Check out"
        uses: actions/checkout@v4
      - name: "Test maven package"
        run: "cd mavenmcserver; mvn package"
  Install:
    runs-on: ubuntu-latest
    steps:
      - name: "Install print"
        run: "echo Install"
