name: "Build & Install action"
run-name: "Running Build & Install action (triggered by ${{ github.actor }})"
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: "Build print"
        run: "echo Build"
      - name: "List workspace directory"
        run: "ls ${{ github.workspace }}"
  Install:
    runs-on: ubuntu-latest
    steps:
      - name: "Install print"
        run: "echo Install"
